#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompleteGolfAppAndroid.Resource", IsApplication=true)]

namespace CompleteGolfAppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int birch = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int coconut = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int elm = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fir = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int larch = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int maple = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int oak = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pine = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int CityText = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int CourseDetailsEdit_Button_AddTee = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int CourseDetailsEdit_Button_Cancel = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int CourseDetailsEdit_Button_Delete = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int CourseDetailsEdit_Button_Save = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int CourseDetailsEdit_EditText_City = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int CourseDetailsEdit_EditText_Holes = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int CourseDetailsEdit_EditText_Name = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int CourseDetailsEdit_EditText_ParTotal = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int CourseDetailsEdit_LinearLayout_HolesPar = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int CourseDetailsEdit_ListView_TeeSummary = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int CourseDetailsEdit_TextView_City = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int CourseDetailsEdit_TextView_HolesCount = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int CourseDetailsEdit_TextView_Name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int CourseDetailsEdit_TextView_Par = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int CourseDetailsView_Button_AddTee = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int CourseDetailsView_LinearLayout_HolesPar = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int CourseDetailsView_ListView_TeeSummary = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int CourseDetailsView_PagerTitleStrip = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int CourseDetailsView_TextView_City = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int CourseDetailsView_TextView_Holes = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int CourseDetailsView_TextView_HolesLabel = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int CourseDetailsView_TextView_Name = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int CourseDetailsView_TextView_Par = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int CourseDetailsView_TextView_ParLabel = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int CourseDetailsView_ViewPager_Holes = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int CourseNameText = 2131034138;
			
			// aapt resource value: 0x7f050025
			public const int CourseTeeDetails_Button_Save = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int CourseTeeDetails_EditText_ReportedYards = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int CourseTeeDetails_LinearLayout_ReportedYards = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int CourseTeeDetails_Spinner_Tee = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int CourseTeeDetails_TextView_Name = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int CourseTeeDetails_TextView_ReportedYards = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int Courses_Button_AddNew = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int Courses_Button_CancelDelete = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int Courses_ListView_CourseList = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int Courses_TextView_Header = 2131034140;
			
			// aapt resource value: 0x7f05002a
			public const int HoleDetails_Button_Cancel = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int HoleDetails_Button_SaveExit = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int HoleDetails_Button_SaveNext = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int HoleDetails_GridView_HoleInfo = 2131034151;
			
			// aapt resource value: 0x7f05002c
			public const int HoleNumberText = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int Home_Button_Courses = 2131034157;
			
			// aapt resource value: 0x7f05002f
			public const int Home_Button_Scores = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int Home_Button_Tees = 2131034158;
			
			// aapt resource value: 0x7f050038
			public const int TeeListActualYardageText = 2131034168;
			
			// aapt resource value: 0x7f050037
			public const int TeeListCourseReportedYardageText = 2131034167;
			
			// aapt resource value: 0x7f050036
			public const int TeeListNameText = 2131034166;
			
			// aapt resource value: 0x7f050034
			public const int TeesDetail_Button_Cancel = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int TeesDetail_Button_Delete = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int TeesDetail_Button_Save = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int TeesDetail_EditText_TeeValue = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int TeesDetail_TextView_TeeLabel = 2131034160;
			
			// aapt resource value: 0x7f05003b
			public const int Tees_Button_AddTee = 2131034171;
			
			// aapt resource value: 0x7f05003a
			public const int Tees_ListView_TeeList = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int Tees_TextView_Label = 2131034169;
			
			// aapt resource value: 0x7f050026
			public const int flash_card_question = 2131034150;
			
			// aapt resource value: 0x7f050019
			public const int lstItemCourse = 2131034137;
			
			// aapt resource value: 0x7f05002b
			public const int lstItemHole = 2131034155;
			
			// aapt resource value: 0x7f050035
			public const int lstItemTee = 2131034165;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CourseDetailsEdit_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CourseDetailsView_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CourseListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Courses_Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CourseTeeDetails_Layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int flashcardlayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HoleDetailsFragment_Layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HoleListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Home_Layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TeeDetails_Layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TeeListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Tees_Layout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
